# .github/workflows/infra.yml

# upon pull request chaning infra files produce a plan and save to that pull request

on: 
    # creates plan on pull request
    pull_request:
        branches: ['master']
        paths: [infra/**]
    # and applies once pushed
    push:
        branches: ['master']
        paths: [infra/**]

# set default region across all jobs, aswell as credentials to allow CLI calls
env: 
  AWS_DEFAULT_REGION: eu-west-2 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:

    plan:

        # define permissions for tokens
        permissions:
          pull-requests: write
          contents: read

        if: github.event_name == 'pull_request'

        runs-on: 'ubuntu-latest'

        steps:
            # clone repo, set up terraform CLI
            - name: clone repo
              uses: actions/checkout@v4
           
            - name: setup terraform
              uses: hashicorp/setup-terraform@v4
            
            
            # then create the plan and save to a file
            - name: init, validate and create terraform plan
              run: |
                terraform init
                terraform validate 
                terraform plan -no-color 2>&1 | tee tf_plan.txt
              # make sure runs in the infra dir!
              working-directory: ./infra/environments/prod
            
            # now post the plan as a comment on the PR
            - name: put plan as comment on PR
              run: |
                gh pr comment ${{ github.event.pull_request.number }} --body "$(cat tf_plan.txt)"
              #  create github token for step only, to auto-allow calls the GitHub API
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              working-directory: ./infra/environments/prod


#################################
# once push to master, apply the changes
    apply:

      if: github.event_name == 'push'
      
      runs-on: 'ubuntu-latest'
      steps:
        
        # clone repo, set up terraform CLI
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3
        # initialise to connect to remote state
        - name: terraform init
          run: |
            terraform init
          working-directory: ./infra/environments/prod
        
        # apply
        - name: apply terraform changes
          run: |
            terraform apply --auto-approve
          working-directory: ./infra/environments/prod
        
        - name: wait for API and lambda to finish updating
          run: |
            sleep 15

############################
# run integration tests after applying terraform changes
    run_final_tests:

      # ensure always runs even if jobs are skipped (or fail, so can get feedback), but only if 
      # event was a push
      if: ${{ always() && github.event_name == 'push'}}

      # only run after applying
      needs: ['apply']

      # run integration tests again afetr apply to make sure that work
      uses: ./.github/workflows/tests.yml
      secrets:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        environment: 'prod'
