# .github/workflows/infra.yml

# creates PR request where changes being made to infrastructure

on: 
    push:
        branches: ['master']
        paths: [infra/**]

# set default region across all jobs, aswell as credentials to allow CLI calls
env: 
  AWS_DEFAULT_REGION: eu-west-2 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

    create_terraform_plan:

        runs-on: 'ubuntu-latest'

        steps:
            # first set up terraform
            - name: setup terraform
              uses: hashicorp/setup-terraform@v4
            
            
            # then create the plan
            - name: create terraform plan
              run: |
                terraform fmt
                terraform init
                terraform validate 
                terraform plan