# .github/workflows/run_tests.yml

# whenever push, do the tests
on:
  push:
    branches: ['master']

jobs:

# first train models and run unit tests (without setting up the API)
  UnitTests:

    # test on linux
    runs-on: 'ubuntu-latest'

    steps:
      # clone repo into runners VM
      - uses: actions/checkout@v5

      # then set up the Kaggle API keys
      - name: set up kaggle keys
        run: |
          mkdir -p ~/.kaggle
          echo '{"key": "${{ secrets.KAGGLE_API_TOKEN }}", "username": "${{ secrets.KAGGLE_USERNAME }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: set up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.14'
          cache: 'pip'
        
      # then install PIP and dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # install project as a package
      - name: install project
        run: pip install -e .

        # now to clean and ingest data, train model and 
      - name: get data and train models
        run: |
          python -m credit_risk_classifier.ingest_and_clean_data
          python -m credit_risk_classifier.train
          python -m credit_risk_classifier.tune

      # save model artifacts for integration test
      - name: upload model artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: trained-models
          path: models/

      # now run tests with Pytest
      - name: do units tests
        run: |
          python -m pytest tests/ -m unit
  
  # test that can get response from API on aws
  awsIntegrationTests:
      # test on linux only for now
      runs-on: ubuntu-latest

      steps:
  # first clone the repo into the runner's VM
      - uses: actions/checkout@v5
  
      - name: set up python
        uses: actions/setup-python@v5
        with: 
            python-version: '3.14'
            cache: 'pip'
          
        # then install PIP and dependencies
      - name: install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        # install project as a package
      - name: install project
        run: pip install -e .

        # run the integration tests
        run: python -m pytest tests/ -m integration