# .github/workflows/run_tests.yml

# whenever push, do the tests
on:
  push:
    branches: ['master']

jobs: 


# first run the unit tests (without API setup)
  UnitTests:

    # test on linux
    runs-on: 'ubuntu-latest'

    # Python version that coded in and more recent version
    strategy:
      matrix:
        python-version: ["3.11", '3.14']
    
    steps:
      # clone repo into runners VM
      - uses: actions/checkout@v5

      # now run tests with Pytest
      - name: do units tests
        run: |
          python -m pytest tests/ -m unit
      
  # Integration test wit container
  # test that works when set up docker
  IntegrationTests:

  # test on linux only for now
      runs-on: ubuntu-latest

      steps:
  # first clone the repo into the runner's VM
      - uses: actions/checkout@v5

        # then set up the Kaggle API keys
      - name: set up kaggle keys
        run: |
          mkdir -p ~/.kaggle
          echo '{"key": "${{ secrets.KAGGLE_API_TOKEN }}", "username": "${{ secrets.KAGGLE_USERNAME }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: set up python
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
        
      # then install PIP and dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # install project as a package
      - name: install project
          run: pip install -e .

        # now to clean and ingest data, train model and 
      - name: get data and train models
        run: |
          python -m credit_risk_classifier.ingest_and_clean_data
          python -m credit_risk_classifier.train
          python -m credit_risk_classifier.tune

  # set up the container
      - name: Start container
        run: docker compose up -d
  # Check server is ready, once the case then move on
      - name: wait for server to be ready
        run: |
          for i in {1..10}; do
            curl http://127.0.0.1:8000/health && break || echo "attempt $i failed, retrying"
            sleep 6
          done

          echo 'check running containers'
            docker ps -a
          echo ' check docker logs'
            docker logs credit_risk_container
  
      # get data and train the models
      - name: get data and train
        run: |
          docker exec -i credit_risk_container python src/ingest_and_clean_data.py
          docker exec -i credit_risk_container python src/train.py
          docker exec -i credit_risk_container python src/tune.py
      # now run test file using pytest
      - name: Run tests using pytest
        run: docker exec -i credit_risk_container python -m pytest tests/ -m integration
  # tear down container afterwards
      - name: tear down container
        run: docker compose down   


        



