# .github/workflows/build.yml

# retrains model and uploads to S3 bucket when changes to src code or config are made
# builds and uploads docker image to ECR when changes to apps are made


# triggers
on:
  push:
    # note that eventually only want to run when push to master?
    branches: ['master', 'devel']
    # whenever change the config or src
    paths: ['src/**', 'config.*']

# set default region across all jobs, aswell as credentials to allow CLI calls
env: 
  AWS_DEFAULT_REGION: eu-west-2 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  # get the files changed during commit as filter for which jobs run
  get_changed_files:

    runs-on: 'ubuntu-latest'
    # set outputs counter for files changed, from the $GITHUB_OUTPUT file
    outputs:
      training_changed: ${{ steps.train_files_check.outputs.TRAINING_CHANGED_COUNT}}
      app_changed: ${{ steps.app_files_check.outputs.APP_CHANGED_COUNT }}

    steps:
      - uses: actions/checkout@v5
        with:
          # get previous commit histroy to enable git diff
          fetch-depth: 2
      
      - id: train_files_check
          # compare file of current vs the previous commit (count num of files changed)
          # for now manual specify which files affect app and which training
        run: |
          echo TRAINING_CHANGED_COUNT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -cE '^src/credit_risk_classifier/t.*\.py|.*config.yml' || echo '0') >> $GITHUB_OUTPUT

      - id: app_files_check
        run: |
          echo APP_CHANGED_COUNT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -cE '.*app\.py|.*inference\.py|.*schemas\.py' || echo '0') >> $GITHUB_OUTPUT

  
  # retrain model when changes made to the training and tuning code
  retrain_model:
    # on linux
    runs-on: 'ubuntu-latest'

    # ensure that only runs once figure out what files have been changed
    needs: get_changed_files

    # if training files have been changed, then run the steps below
    if: needs.get_changed_files.outputs.training_changed > 0

    steps:
      # clone repo
      - uses: actions/checkout@v5

       # then set up the Kaggle API keys
      - name: set up kaggle keys
        run: |
          mkdir -p ~/.kaggle
          echo '{"key": "${{ secrets.KAGGLE_API_TOKEN }}", "username": "${{ secrets.KAGGLE_USERNAME }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # set up python with same version as docker file
      - name: set up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
          # cache environment for faster loading of requirements later
          cache: 'pip'
        
      # then install PIP and dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # install project as a package
      - name: install project
        run: pip install -e .
      

      # now retrain model, (so can auto push model artifact to s3)
      - name: get data and train models
        run: |
          python -m credit_risk_classifier.ingest_and_clean_data
          python -m credit_risk_classifier.train
          python -m credit_risk_classifier.tune
      
      
      # define model key name using commit hash (Append to GITHUB env so persists across steps.)
      - name: create model key name
        id: create_model_key_name
        run: |
            echo "MODEL_KEY_NAME=$(models/${{ github.sha }}).pkl" >> $GITHUB_ENV

      # get bucket name to save artifact to.
      - name: get bucket name
        run: |
          echo "MODEL_BUCKET_NAME=$(aws ssm get-parameter  --name model_bucket_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV

      # push model artifact to S3
      - name: save model artifact to s3 (for now choose production model here)
        run: |
          aws s3 cp "models/tuned/xgb/standard.pkl" "s3://${MODEL_BUCKET_NAME}/${MODEL_KEY_NAME}"
      
      # update ssm parameter for the model key name
      - name: update SSM image uri
        run: |
          aws ssm put-parameter  --name model_key_name --overwrite --value $MODEL_KEY_NAME

###########################################

  # push new image when changes made to the app
  push_docker_image:
    runs-on: 'ubuntu-latest'

    # must wait for job that figures out which files have been changed
    needs: get_changed_files

    if: needs.get_changed_files.outputs.app_changed > 0

    steps:

    # clone repo
      - uses: actions/checkout@v5
    
    # get the ECR repo url and lambda function name from AWS SSM
      - name: get ecr url and lambda function name
        run: |
          echo "ECR_REPO_URL=$(aws ssm get-parameter --name ecr_repo_url --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
          echo "LAMBDA_FUNC_NAME=$(aws ssm get-parameter --name lambda_function_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
    
    # build the docker image and push to ECR
      - name: build the docker image and push to ECR
      # need to authenticate first before pushing. Using git commit hash for the image tag
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 772928963391.dkr.ecr.eu-west-2.amazonaws.com
          docker buildx build \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          --provenance=False --platform=linux/amd64 \
          -t $ECR_REPO_URL:${{ github.sha }} \
          --push .
    
    # now that pushed to ECR, update AWS SSM parameter with the new image URL
      - name: update SSM image uri
        run: |
          aws ssm put-parameter  --name image_uri --overwrite --value $ECR_REPO_URL:${{ github.sha }}

#######################
# apply terraform changes (for now, just apply because only changing image and key name)
# in future, will use seperate dev environment
  apply_terraform_changes:

    # only runs when the previous jobs have not failed
    if: ${{ always() && needs.retrain_model.result != 'failure' && needs.push_docker_image.result != 'failure' }}
    needs: ['retrain_model', 'push_docker_image']

    runs-on: 'ubuntu-latest'
    steps:
            # clone repo, set up terraform CLI
            - name: clone repo
              uses: actions/checkout@v4
           
            # load in image uri and model key name from ssm
            - name: get ssm params
              run: |
                echo "IMAGE_URI=$(aws ssm get-parameter --name image_uri --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
                echo "MODEL_KEY_NAME=$(aws ssm get-parameter --name model_key_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV

            - name: setup terraform
              uses: hashicorp/setup-terraform@v4
            
            
            # then create the plan and save to a file
            - name: init, validate
              run: |
                terraform init
                terraform validate 
              # make sure runs in the infra dir!
              working-directory: ./infra
            
            # and apply changes (to devel environment)
            - name: apply terraform changes
              run: |
                terraform apply --auto-approve -var "image_uri=${IMAGE_URI}" -var "model_key_name=${MODEL_KEY_NAME}"
              working-directory: ./infra



####################################
  # unit and integration tests
  test:

    # only run afetr terraform update step completed
    # must wait for 
    needs: ['apply_terraform_changes']

    # use test workflow
    uses: ./.github/workflows/tests.yml
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
        
        