# .github/workflows/build.yml

# retrains model and uploads to S3 bucket when changes to src code or config are made
# builds and uploads docker image to ECR when changes to apps are made


# triggers
on:
  push:
    branches: ['master', 'devel']
    # whenever change the config or src
    paths: ['src/**', 'config.*']

# set default region across all jobs, aswell as credentials to allow CLI calls
env: 
  AWS_DEFAULT_REGION: eu-west-2 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  # get the files changed during commit as filter for which jobs run
  get_changed_files:

    runs-on: 'ubuntu-latest'
    # set outputs counter for files changed, from the $GITHUB_OUTPUT file
    outputs:
      training_changed: ${{ steps.train_files_check.outputs.TRAINING_CHANGED_COUNT}}
      app_changed: ${{ steps.app_files_check.outputs.APP_CHANGED_COUNT }}

    steps:
      - uses: actions/checkout@v5
        with:
          # get previous commit histroy to enable git diff
          fetch-depth: 2
      
      - id: train_files_check
          # compare file of current vs the previous commit (count num of files changed)
          # for now manual specify which files affect app and which training
        run: |
          echo TRAINING_CHANGED_COUNT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -cE '^src/credit_risk_classifier/t.*\.py|.*config.yml' || echo '0') >> $GITHUB_OUTPUT

      - id: app_files_check
        run: |
          echo APP_CHANGED_COUNT=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -cE '.*app\.py|.*inference\.py|.*schemas\.py' || echo '0') >> $GITHUB_OUTPUT

  
  # retrain model when changes made to the training and tuning code
  retrain_model:
    # on linux
    runs-on: 'ubuntu-latest'

    # ensure that only runs once figure out what files have been changed
    needs: get_changed_files

    # if training files have been changed, then run the steps below
    if: needs.get_changed_files.outputs.training_changed > 0

    steps:
      # clone repo
      - uses: actions/checkout@v5

       # then set up the Kaggle API keys
      - name: set up kaggle keys
        run: |
          mkdir -p ~/.kaggle
          echo '{"key": "${{ secrets.KAGGLE_API_TOKEN }}", "username": "${{ secrets.KAGGLE_USERNAME }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # set up python with version 3.14
      - name: set up python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.14'
          # cache environment for faster loading of requirements later
          cache: 'pip'
        
      # then install PIP and dependencies
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # install project as a package
      - name: install project
        run: pip install -e .
      

      # now retrain model, (so can auto push model artifact to s3)
      - name: get data and train models
        run: |
          python -m credit_risk_classifier.ingest_and_clean_data
          python -m credit_risk_classifier.train
          python -m credit_risk_classifier.tune
      
      
      # get bucket and artifact name to save artifact to 
      # for now always using same model which defined as key_name (so no need to update the key name)
      - name: get SSM params
        id: get_SSM_params
        
      # append to GITHUB env so persists across steps
        run: |
          echo "MODEL_BUCKET_NAME=$(aws ssm get-parameter  --name model_bucket_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
          echo "MODEL_KEY_NAME=$(aws ssm get-parameter  --name model_key_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
          echo "the model bucket name is ${MODEL_BUCKET_NAME} and model key name ${MODEL_KEY_NAME}"
      # push model artifact to S3 (using env variables defined above for the bucket name)
      - name: save model artifact to s3
        run: |
          aws s3  cp "models/tuned/xgb/$MODEL_KEY_NAME" "s3://$MODEL_BUCKET_NAME"
        
###########################################

  # push new image when changes made to the app
  push_docker_image:
    runs-on: 'ubuntu-latest'

    # must wait for job that figures out which files have been changed
    needs: get_changed_files

    if: needs.get_changed_files.outputs.app_changed > 0

    steps:

    # clone repo
      - uses: actions/checkout@v5
    
    # get the ECR repo url and lambda function name from AWS SSM
      - name: get ecr url and lambda function name
        run: |
          echo "ECR_REPO_URL=$(aws ssm get-parameter --name ecr_repo_url --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
          echo "LAMBDA_FUNC_NAME=$(aws ssm get-parameter --name lambda_function_name --query 'Parameter.Value' --output text | tr -d '"')" >> $GITHUB_ENV
    
    # build the docker image and push to ECR
      - name: build the docker image and push to ECR
      # need to authenticate first before pushing. Using git commit hash for the image tag
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 772928963391.dkr.ecr.eu-west-2.amazonaws.com
          docker buildx build \
          --cache-from type=gha \
          --cache-to type=gha,mode=max \
          --provenance=False --platform=linux/amd64 \
          -t $ECR_REPO_URL:${{ github.sha }} \
          --push .
    
    # now that pushed to ECR, update AWS SSM parameter with the new image URL
      - name: update SSM image uri
        run: |
          aws ssm put-parameter  --name image_uri --overwrite --value $ECR_REPO_URL:${{ github.sha }}
    
    # update lambda function via aws CLI (not using Terraform here. When next apply, lambda is configured so 
    # that will be set to the SSM image URI anyway)
      - name: update lambda function
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNC_NAME --image-uri $ECR_REPO_URL:${{ github.sha }}
    

####################################
  # unit and integration tests
  tests:

    # ensure always runs even if jobs are skipped (or fail, so can get feedback)
    if: ${{ always() }}
    # must wait for building or retraining to finish
    needs: ['retrain_model', 'push_docker_image']

    # use test workflow
    uses: ./.github/workflows/tests.yml
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
        
        